runtime: php74

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:jPYYvMMf4BqWp1tN5MhijMZGDL6cakwh4J9BLaISsUs=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: saveoury_db
  DB_USERNAME: root
  DB_PASSWORD: b4ngk!t2021
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/saveoury-backend:us-central1:saveoury"
  ## for PostgreSQL, use DB_HOST:
  # DB_HOST: "/cloudsql/YOUR_CONNECTION_NAME"
